version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - sqlite_data:/app/sqlite_data
    ports:
      - "80:8080"
    restart: always   
    environment:
      DEBUG: "1"
      DJANGO_SECRET_KEY: supersecretkey

volumes:
  sqlite_data: