# Generated by Django 5.2.3 on 2025-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="To Do",
                max_length=20,
            ),
        ),
    ]
